repos:
  - repo: local
    hooks: 
      - id: black
        name: black
        entry: poetry run black .
        language: system
        always_run: true
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: poetry run pytest
        language: system
        always_run: true
        pass_filenames: false
